# TASK 1 CREATE A NAME VARIABLE AND STORE YOUR NAME
name="Muhammad Yasir"
print(name)
# TASK 2 CREATE A VARIABLE CALLED AGE AND STORE YOUR AGE
age=20
print(age)
# TASK 3 CREATE A VARIABLE CALLED COUNTRY AND STORE YOUR COUNTRY
country="PAKISTAN"
print(country)
# TASK 4 CREATE A VARIABLE NAMED total THAT STORES THEIR SUM
num1=15
num2=25
total=num1+num2
print(total)
# MINI CHALLANGE:STORE FIRST NAME AND LAST NAME IN SEPARATE 
first_name="Muhammad"
last_name="Yasir"
print(first_name,last_name)
