# Create a variable name and store your full name. Then print it
name="Muhammad Yasir"
print(name)
# create a variable age and store your age. Print it
age=20
print(age)
# Create two variables
city="Hangu"
country="Pakistan"
print(city,country)
# What will be the output x=10 and x=20
x=10
x=20
print(x)
# Fix the error name = Yasir print(name)
name="Yasir"
print(name)
# Create variables a=15 b = 5 find sum,difference and multiplication 
# find all results
a=15
b=5
print(a+b)
print(a-b)
print(a*b)
# Predict output:
x = 5
y = x + 10
x = 20
print(y)
# Write a program that stores your name stores your age stores your country
# Then prints like this My name is ___, I am ___ years old and I live in ___.
name="Muhammad Yasir"
age=20
country="Pakistan"
print("My name is (name),I am (age) years and I live in (country)")
# What is wrong here 1name = "Ali" print(1name)
name1="Ali"
print(name1)
# Swap values a = 10 b = 20 make a=20 and b=10 Without writing direct values again
a=10
b=20
print(a=b)