# ARITHMETIC OPERATORS
a=2
b=3
c=4
d=5
e=6
f=7
g=8
h=9
print(a+b)
print(c-d)
print(e*f)
print(g/h)
# ASSIGNMENT OPERATORS
i=2
i+=3
j=4
j-=2
k=5
k*=6
l=8
l/=4
print(i,j,k,l)
# COMPARISON OPERATORS
m=5==5
n=5>4
o=5<6
p=5>=6
q=5<=4
r=7!=8
print(m,n,o,p,q,r)
# LOGICAL OPERATORS OR,AND,NOT
# TRUTH TABLE OF OR
print("True or false is",True or False)
print("True or True is",True or False)
print("False or True is",True or False)
print("False or False is",True or False)
# TRUTH TABLE OF AND
print("True and false is",True and False)
print("True and True is",True and False)
print("False and True is",True and False)
print("False and False is",True and False)
# for NOT
print(not(True))
print(not(False))