'''Create two variables a = 15 and b = 4, then print:
Addition
Subtraction
Multiplication
Division
Find the remainder when 25 is divided by 7.
Calculate 3 raised to the power of 4.'''
a=15
b=4
print(a+b,a-b,a*b,a/b)
c=25%7
print(c)
d=3**4
print(d)
# START WITH X=20 APPLY X+=10 X*=2
x=20
x+=10
x*=2
print(x)
# Check whether 50 is greater than 20 and less than 100
print(50>20 and 50<100)


"""
Write a program that:
Stores a user's age.
Prints "Eligible" if the age is 18 or above.
Otherwise, prints "Not Eligible"."""
age=20
print("eligible",(age>=18))